function[]=compute_boun_corre_point_info(size_out_fic_for_in,d_x,d_y,nonlocal_size,r)
    global in_cross_boun_mark
    global out_index_x
    global out_index_y
    global boun_point_posi
    global sym_boun_point_posi
    global sym_left_info
    global sym_right_info
    global sym_down_info
    global sym_upper_info
    global finite_dis
    
    left_x=nonlocal_size(1);
    right_x=nonlocal_size(2);
    down_y=nonlocal_size(3);
    upper_y=nonlocal_size(4);
    left_range=left_x*d_x;
    right_range=right_x*d_x;
    down_range=down_y*d_y;
    upper_range=upper_y*d_y;
    
    for i=1:1:size_out_fic_for_in
        global_x=out_index_x(i);
        global_y=out_index_y(i);
        boun_1=in_cross_boun_mark(global_x,global_y,1);
        boun_2=in_cross_boun_mark(global_x,global_y,2);
        if(boun_1==-1)
            if(boun_2==1)
                sym_boun_point_posi(i,1,1)=2*(global_x-1)*d_x-boun_point_posi(i,1,1);
                sym_boun_point_posi(i,1,2)=(global_y-1)*d_y;
                sym_boun_point_posi(i,1,3)=1;
                finite_dis(i,1)=boun_point_posi(i,1,1)-(global_x-1)*d_x;
                a_posi_x=sym_boun_point_posi(i,1,1);
                a_posi_y=sym_boun_point_posi(i,1,2);
                l_range=max(a_posi_x-left_range,0);
                if(a_posi_x==l_range)
                    sym_left_info(i,1,2)=0;
                else
                    if(ceil(l_range/d_x)-l_range/d_x<1e-4)
                        b=ceil(l_range/d_x);
                    else
                        b=floor(l_range/d_x);
                    end
                    if((a_posi_x/d_x)-floor(a_posi_x/d_x)<1e-4)
                        a=floor(a_posi_x/d_x);
                    else
                        a=ceil(a_posi_x/d_x);
                    end
                    sym_left_info(i,1,2)=a-b;
                end
                sym_left_info(i,1,1)=l_range;
                sym_left_info(i,1,3)=0>a_posi_x-left_range;
                d_range=max(a_posi_y-down_range,0);
                if(a_posi_y==d_range)
                    sym_down_info(i,1,2)=0;
                else
                    if(ceil(d_range/d_y)-d_range/d_y<1e-4)
                        b=ceil(d_range/d_y);
                    else
                        b=floor(d_range/d_y);
                    end
                    if((a_posi_y/d_y)-floor(a_posi_y/d_y)<1e-4)
                        a=floor(a_posi_y/d_y);
                    else
                        a=ceil(a_posi_y/d_y);
                    end
                    sym_down_info(i,1,2)=a-b;
                end
                sym_down_info(i,1,1)=d_range;
                sym_down_info(i,1,3)=0>a_posi_y-down_range;
                dis_x=r;
                r_range=min(a_posi_x+right_range,dis_x);
                if(a_posi_x==r_range)
                    sym_right_info(i,1,2)=0;
                else
                    if((r_range/d_x-floor(r_range/d_x))<1e-4)
                        a=floor(r_range/d_x);
                    else
                        a=ceil(r_range/d_x);
                    end
                    if((ceil(a_posi_x/d_x)-a_posi_x/d_x)<1e-4)
                        b=ceil(a_posi_x/d_x);
                    else
                        b=floor(a_posi_x/d_x);
                    end
                    sym_right_info(i,1,2)=a-b;
                end
                sym_right_info(i,1,1)=r_range;
                sym_right_info(i,1,3)=dis_x<a_posi_x+right_range;
                dis_y=sqrt(r^2-a_posi_x^2);
                u_range=min(a_posi_y+upper_range,dis_y);
                if(a_posi_y==u_range)
                    sym_upper_info(i,1,2)=0;
                else
                    if((u_range/d_y-floor(u_range/d_y))<1e-4)
                        a=floor(u_range/d_y);
                    else
                        a=ceil(u_range/d_y);
                    end
                    if((ceil(a_posi_y/d_y)-a_posi_y/d_y)<1e-4)
                        b=ceil(a_posi_y/d_y);
                    else
                        b=floor(a_posi_y/d_y);
                    end
                    sym_upper_info(i,1,2)=a-b;
                end
                sym_upper_info(i,1,1)=u_range;
                sym_upper_info(i,1,3)=dis_y<a_posi_y+upper_range;
            else
                sym_boun_point_posi(i,1,2)=2*(global_y-1)*d_y-boun_point_posi(i,1,2);
                sym_boun_point_posi(i,1,1)=(global_x-1)*d_x;
                sym_boun_point_posi(i,1,3)=2;
                finite_dis(i,2)=boun_point_posi(i,1,2)-(global_y-1)*d_y;
                a_posi_x=sym_boun_point_posi(i,1,1);
                a_posi_y=sym_boun_point_posi(i,1,2);
                l_range=max(a_posi_x-left_range,0);
                if(a_posi_x==l_range)
                    sym_left_info(i,1,2)=0;
                else
                    if(ceil(l_range/d_x)-l_range/d_x<1e-4)
                        b=ceil(l_range/d_x);
                    else
                        b=floor(l_range/d_x);
                    end
                    if((a_posi_x/d_x)-floor(a_posi_x/d_x)<1e-4)
                        a=floor(a_posi_x/d_x);
                    else
                        a=ceil(a_posi_x/d_x);
                    end
                    sym_left_info(i,1,2)=a-b;
                end
                sym_left_info(i,1,1)=l_range;
                sym_left_info(i,1,3)=0>a_posi_x-left_range;
                d_range=max(a_posi_y-down_range,0);
                if(a_posi_y==d_range)
                    sym_down_info(i,1,2)=0;
                else
                    if(ceil(d_range/d_y)-d_range/d_y<1e-4)
                        b=ceil(d_range/d_y);
                    else
                        b=floor(d_range/d_y);
                    end
                    if((a_posi_y/d_y)-floor(a_posi_y/d_y)<1e-4)
                        a=floor(a_posi_y/d_y);
                    else
                        a=ceil(a_posi_y/d_y);
                    end
                    sym_down_info(i,1,2)=a-b;
                end
                sym_down_info(i,1,1)=d_range;
                sym_down_info(i,1,3)=0>a_posi_y-down_range;
                dis_x=sqrt(r^2-a_posi_y^2);
                r_range=min(a_posi_x+right_range,dis_x);
                if(a_posi_x==r_range)
                    sym_right_info(i,1,2)=0;
                else
                    if((r_range/d_x-floor(r_range/d_x))<1e-4)
                        a=floor(r_range/d_x);
                    else
                        a=ceil(r_range/d_x);
                    end
                    if((ceil(a_posi_x/d_x)-a_posi_x/d_x)<1e-4)
                        b=ceil(a_posi_x/d_x);
                    else
                        b=floor(a_posi_x/d_x);
                    end
                    sym_right_info(i,1,2)=a-b;
                end
                sym_right_info(i,1,1)=r_range;
                sym_right_info(i,1,3)=dis_x<a_posi_x+right_range;
                dis_y=r;
                u_range=min(a_posi_y+upper_range,dis_y);
                if(a_posi_y==u_range)
                    sym_upper_info(i,1,2)=0;
                else
                    if((u_range/d_y-floor(u_range/d_y))<1e-4)
                        a=floor(u_range/d_y);
                    else
                        a=ceil(u_range/d_y);
                    end
                    if((ceil(a_posi_y/d_y)-a_posi_y/d_y)<1e-4)
                        b=ceil(a_posi_y/d_y);
                    else
                        b=floor(a_posi_y/d_y);
                    end
                    sym_upper_info(i,1,2)=a-b;
                end
                sym_upper_info(i,1,1)=u_range;
                sym_upper_info(i,1,3)=dis_y<a_posi_y+upper_range;
            end
        elseif((boun_1==1)||(boun_1==5))
            if(((boun_1==1)&&(boun_2==1))||((boun_1==5)&&(boun_2==2)))
                sym_boun_point_posi(i,1,1)=2*(global_x-1)*d_x-boun_point_posi(i,1,1);
                sym_boun_point_posi(i,1,2)=(global_y-1)*d_y;
                sym_boun_point_posi(i,1,3)=1;
                finite_dis(i,1)=boun_point_posi(i,1,1)-(global_x-1)*d_x;
                a_posi_x=sym_boun_point_posi(i,1,1);
                a_posi_y=sym_boun_point_posi(i,1,2);
                l_range=max(a_posi_x-left_range,0);
                if(a_posi_x==l_range)
                    sym_left_info(i,1,2)=0;
                else
                    if(ceil(l_range/d_x)-l_range/d_x<1e-4)
                        b=ceil(l_range/d_x);
                    else
                        b=floor(l_range/d_x);
                    end
                    if((a_posi_x/d_x)-floor(a_posi_x/d_x)<1e-4)
                        a=floor(a_posi_x/d_x);
                    else
                        a=ceil(a_posi_x/d_x);
                    end
                    sym_left_info(i,1,2)=a-b;
                end
                sym_left_info(i,1,1)=l_range;
                sym_left_info(i,1,3)=0>a_posi_x-left_range;
                d_range=max(a_posi_y-down_range,0);
                if(a_posi_y==d_range)
                    sym_down_info(i,1,2)=0;
                else
                    if(ceil(d_range/d_y)-d_range/d_y<1e-4)
                        b=ceil(d_range/d_y);
                    else
                        b=floor(d_range/d_y);
                    end
                    if((a_posi_y/d_y)-floor(a_posi_y/d_y)<1e-4)
                        a=floor(a_posi_y/d_y);
                    else
                        a=ceil(a_posi_y/d_y);
                    end
                    sym_down_info(i,1,2)=a-b;
                end
                sym_down_info(i,1,1)=d_range;
                sym_down_info(i,1,3)=0>a_posi_y-down_range;
                dis_x=boun_point_posi(i,1,1);
                r_range=min(a_posi_x+right_range,dis_x);
                if(a_posi_x==r_range)
                    sym_right_info(i,1,2)=0;
                else
                    if((r_range/d_x-floor(r_range/d_x))<1e-4)
                        a=floor(r_range/d_x);
                    else
                        a=ceil(r_range/d_x);
                    end
                    if((ceil(a_posi_x/d_x)-a_posi_x/d_x)<1e-4)
                        b=ceil(a_posi_x/d_x);
                    else
                        b=floor(a_posi_x/d_x);
                    end
                    sym_right_info(i,1,2)=a-b;
                end
                sym_right_info(i,1,1)=r_range;
                sym_right_info(i,1,3)=dis_x<a_posi_x+right_range;
                dis_y=sqrt(r^2-a_posi_x^2);
                u_range=min(a_posi_y+upper_range,dis_y);
                if(a_posi_y==u_range)
                    sym_upper_info(i,1,2)=0;
                else
                    if((u_range/d_y-floor(u_range/d_y))<1e-4)
                        a=floor(u_range/d_y);
                    else
                        a=ceil(u_range/d_y);
                    end
                    if((ceil(a_posi_y/d_y)-a_posi_y/d_y)<1e-4)
                        b=ceil(a_posi_y/d_y);
                    else
                        b=floor(a_posi_y/d_y);
                    end
                    sym_upper_info(i,1,2)=a-b;
                end
                sym_upper_info(i,1,1)=u_range;
                sym_upper_info(i,1,3)=dis_y<a_posi_y+upper_range;
            elseif(((boun_1==1)&&(boun_2==2))||((boun_1==5)&&(boun_2==1)))
                sym_boun_point_posi(i,1,2)=2*(global_y-1)*d_y-boun_point_posi(i,1,2);
                sym_boun_point_posi(i,1,1)=(global_x-1)*d_x;
                sym_boun_point_posi(i,1,3)=2;
                finite_dis(i,2)=boun_point_posi(i,1,2)-(global_y-1)*d_y;
                a_posi_x=sym_boun_point_posi(i,1,1);
                a_posi_y=sym_boun_point_posi(i,1,2);
                l_range=max(a_posi_x-left_range,0);
                if(a_posi_x==l_range)
                    sym_left_info(i,1,2)=0;
                else
                    if(ceil(l_range/d_x)-l_range/d_x<1e-4)
                        b=ceil(l_range/d_x);
                    else
                        b=floor(l_range/d_x);
                    end
                    if((a_posi_x/d_x)-floor(a_posi_x/d_x)<1e-4)
                        a=floor(a_posi_x/d_x);
                    else
                        a=ceil(a_posi_x/d_x);
                    end
                    sym_left_info(i,1,2)=a-b;
                end
                sym_left_info(i,1,1)=l_range;
                sym_left_info(i,1,3)=0>a_posi_x-left_range;
                d_range=max(a_posi_y-down_range,0);
                if(a_posi_y==d_range)
                    sym_down_info(i,1,2)=0;
                else
                    if(ceil(d_range/d_y)-d_range/d_y<1e-4)
                        b=ceil(d_range/d_y);
                    else
                        b=floor(d_range/d_y);
                    end
                    if((a_posi_y/d_y)-floor(a_posi_y/d_y)<1e-4)
                        a=floor(a_posi_y/d_y);
                    else
                        a=ceil(a_posi_y/d_y);
                    end
                    sym_down_info(i,1,2)=a-b;
                end
                sym_down_info(i,1,1)=d_range;
                sym_down_info(i,1,3)=0>a_posi_y-down_range;
                dis_x=sqrt(r^2-a_posi_y^2);
                r_range=min(a_posi_x+right_range,dis_x);
                if(a_posi_x==r_range)
                    sym_right_info(i,1,2)=0;
                else
                    if((r_range/d_x-floor(r_range/d_x))<1e-4)
                        a=floor(r_range/d_x);
                    else
                        a=ceil(r_range/d_x);
                    end
                    if((ceil(a_posi_x/d_x)-a_posi_x/d_x)<1e-4)
                        b=ceil(a_posi_x/d_x);
                    else
                        b=floor(a_posi_x/d_x);
                    end
                    sym_right_info(i,1,2)=a-b;
                end
                sym_right_info(i,1,1)=r_range;
                sym_right_info(i,1,3)=dis_x<a_posi_x+right_range;
                dis_y=boun_point_posi(i,1,2);
                u_range=min(a_posi_y+upper_range,dis_y);
                if(a_posi_y==u_range)
                    sym_upper_info(i,1,2)=0;
                else
                    if((u_range/d_y-floor(u_range/d_y))<1e-4)
                        a=floor(u_range/d_y);
                    else
                        a=ceil(u_range/d_y);
                    end
                    if((ceil(a_posi_y/d_y)-a_posi_y/d_y)<1e-4)
                        b=ceil(a_posi_y/d_y);
                    else
                        b=floor(a_posi_y/d_y);
                    end
                    sym_upper_info(i,1,2)=a-b;
                end
                sym_upper_info(i,1,1)=u_range;
                sym_upper_info(i,1,3)=dis_y<a_posi_y+upper_range;
            end
        elseif(boun_1==2)
            
        elseif((boun_1==3)||(boun_1==4))
            %first direction
            sym_boun_point_posi(i,1,1)=2*(global_x-1)*d_x-boun_point_posi(i,1,1);
            sym_boun_point_posi(i,1,2)=(global_y-1)*d_y;
            sym_boun_point_posi(i,1,3)=1;
            finite_dis(i,1)=boun_point_posi(i,1,1)-(global_x-1)*d_x;
            a_posi_x=sym_boun_point_posi(i,1,1);
            a_posi_y=sym_boun_point_posi(i,1,2);
            l_range=max(a_posi_x-left_range,0);
            if(a_posi_x==l_range)
                sym_left_info(i,1,2)=0;
            else
                if(ceil(l_range/d_x)-l_range/d_x<1e-4)
                    b=ceil(l_range/d_x);
                else
                    b=floor(l_range/d_x);
                end
                if((a_posi_x/d_x)-floor(a_posi_x/d_x)<1e-4)
                    a=floor(a_posi_x/d_x);
                else
                    a=ceil(a_posi_x/d_x);
                end
                sym_left_info(i,1,2)=a-b;
            end
            sym_left_info(i,1,1)=l_range;
            sym_left_info(i,1,3)=0>a_posi_x-left_range;
            d_range=max(a_posi_y-down_range,0);
            if(a_posi_y==d_range)
                sym_down_info(i,1,2)=0;
            else
                if(ceil(d_range/d_y)-d_range/d_y<1e-4)
                    b=ceil(d_range/d_y);
                else
                    b=floor(d_range/d_y);
                end
                if((a_posi_y/d_y)-floor(a_posi_y/d_y)<1e-4)
                    a=floor(a_posi_y/d_y);
                else
                    a=ceil(a_posi_y/d_y);
                end
                sym_down_info(i,1,2)=a-b;
            end
            sym_down_info(i,1,1)=d_range;
            sym_down_info(i,1,3)=0>a_posi_y-down_range;
            dis_x=boun_point_posi(i,1,1);
            r_range=min(a_posi_x+right_range,dis_x);
            if(a_posi_x==r_range)
                sym_right_info(i,1,2)=0;
            else
                if((r_range/d_x-floor(r_range/d_x))<1e-4)
                    a=floor(r_range/d_x);
                else
                    a=ceil(r_range/d_x);
                end
                if((ceil(a_posi_x/d_x)-a_posi_x/d_x)<1e-4)
                    b=ceil(a_posi_x/d_x);
                else
                    b=floor(a_posi_x/d_x);
                end
                sym_right_info(i,1,2)=a-b;
            end
            sym_right_info(i,1,1)=r_range;
            sym_right_info(i,1,3)=dis_x<a_posi_x+right_range;
            dis_y=sqrt(r^2-a_posi_x^2);
            u_range=min(a_posi_y+upper_range,dis_y);
            if(a_posi_y==u_range)
                sym_upper_info(i,1,2)=0;
            else
                if((u_range/d_y-floor(u_range/d_y))<1e-4)
                    a=floor(u_range/d_y);
                else
                    a=ceil(u_range/d_y);
                end
                if((ceil(a_posi_y/d_y)-a_posi_y/d_y)<1e-4)
                    b=ceil(a_posi_y/d_y);
                else
                    b=floor(a_posi_y/d_y);
                end
                sym_upper_info(i,1,2)=a-b;
            end
            sym_upper_info(i,1,1)=u_range;
            sym_upper_info(i,1,3)=dis_y<a_posi_y+upper_range;
            % second direction
            sym_boun_point_posi(i,2,2)=2*(global_y-1)*d_y-boun_point_posi(i,2,2);
            sym_boun_point_posi(i,2,1)=(global_x-1)*d_x;
            sym_boun_point_posi(i,2,3)=2;
            finite_dis(i,2)=boun_point_posi(i,2,2)-(global_y-1)*d_y;
            b_posi_x=sym_boun_point_posi(i,2,1);
            b_posi_y=sym_boun_point_posi(i,2,2);
            l_range=max(b_posi_x-left_range,0);
            if(b_posi_x==l_range)
                sym_left_info(i,2,2)=0;
            else
                if(ceil(l_range/d_x)-l_range/d_x<1e-4)
                    b=ceil(l_range/d_x);
                else
                    b=floor(l_range/d_x);
                end
                if((b_posi_x/d_x)-floor(b_posi_x/d_x)<1e-4)
                    a=floor(b_posi_x/d_x);
                else
                    a=ceil(b_posi_x/d_x);
                end
                sym_left_info(i,2,2)=a-b;
            end
            sym_left_info(i,2,1)=l_range;
            sym_left_info(i,2,3)=0>b_posi_x-left_range;
            d_range=max(b_posi_y-down_range,0);
            if(b_posi_y==d_range)
                sym_down_info(i,2,2)=0;
            else
                if(ceil(d_range/d_y)-d_range/d_y<1e-4)
                    b=ceil(d_range/d_y);
                else
                    b=floor(d_range/d_y);
                end
                if((b_posi_y/d_y)-floor(b_posi_y/d_y)<1e-4)
                    a=floor(b_posi_y/d_y);
                else
                    a=ceil(b_posi_y/d_y);
                end
                sym_down_info(i,2,2)=a-b;
            end
            sym_down_info(i,2,1)=d_range;
            sym_down_info(i,2,3)=0>b_posi_y-down_range;
            dis_x=sqrt(r^2-b_posi_y^2);
            r_range=min(b_posi_x+right_range,dis_x);
            
            if(b_posi_x==r_range)
                sym_right_info(i,2,2)=0;
            else
                if((r_range/d_x-floor(r_range/d_x))<1e-4)
                    a=floor(r_range/d_x);
                else
                    a=ceil(r_range/d_x);
                end
                if((ceil(b_posi_x/d_x)-b_posi_x/d_x)<1e-4)
                    b=ceil(b_posi_x/d_x);
                else
                    b=floor(b_posi_x/d_x);
                end
                sym_right_info(i,2,2)=a-b;
            end
            sym_right_info(i,2,1)=r_range;
            sym_right_info(i,2,3)=dis_x<b_posi_x+right_range;
            dis_y=boun_point_posi(i,2,2);
            u_range=min(b_posi_y+upper_range,dis_y);
            if(b_posi_y==u_range)
                sym_upper_info(i,2,2)=0;
            else
                if((u_range/d_y-floor(u_range/d_y))<1e-4)
                    a=floor(u_range/d_y);
                else
                    a=ceil(u_range/d_y);
                end
                if((ceil(b_posi_y/d_y)-b_posi_y/d_y)<1e-4)
                    b=ceil(b_posi_y/d_y);
                else
                    b=floor(b_posi_y/d_y);
                end
                sym_upper_info(i,2,2)=a-b;
            end
            sym_upper_info(i,2,1)=u_range;
            sym_upper_info(i,2,3)=dis_y<b_posi_y+upper_range;
        end
    end
end