function[results]=single_point_derivative(nine_point_x,nine_point_y,posi,center_coord,d_x,d_y,rela_point_posi,deri_direction)
    % rela_point_posi:
    % rela_point_posi==1:
    % upper_right
    % rela_point_posi==2:
    % upper_left
    % rela_point_posi==3:
    % down_left
    % rela_point_posi==4:
    % down_right
    posi_x=posi(1);
    posi_y=posi(2);
    if(rela_point_posi==1)
        floor_x=center_coord(1);
        floor_y=center_coord(2);
        if(deri_direction==1)% compute x direction derivative
            x_disp=nine_point_x(3:-1:1,1);
            left2_disp_x=second_order_interpolation(x_disp,posi_y,floor_y,0,d_x,d_y,1);
            y_disp=nine_point_y(3:-1:1,1);
            left2_disp_y=second_order_interpolation(y_disp,posi_y,floor_y,0,d_x,d_y,1);
            x_disp=nine_point_x(3:-1:1,2);
            left_disp_x=second_order_interpolation(x_disp,posi_y,floor_y,0,d_x,d_y,1);
            y_disp=nine_point_y(3:-1:1,2);
            left_disp_y=second_order_interpolation(y_disp,posi_y,floor_y,0,d_x,d_y,1);
            x_disp=nine_point_x(3:-1:1,3);
            right_disp_x=second_order_interpolation(x_disp,posi_y,floor_y,0,d_x,d_y,1);
            y_disp=nine_point_y(3:-1:1,3);
            right_disp_y=second_order_interpolation(y_disp,posi_y,floor_y,0,d_x,d_y,1);
            x_disp=[left2_disp_x;left_disp_x;right_disp_x];
            deri_x_disp_x=second_order_interpolation(x_disp,posi_x,floor_x,1,d_x,d_y,2);
            y_disp=[left2_disp_y;left_disp_y;right_disp_y];
            deri_x_disp_y=second_order_interpolation(y_disp,posi_x,floor_x,1,d_x,d_y,2);
            results(1)=deri_x_disp_x;
            results(2)=deri_x_disp_y;
        else% compute y direction derivative
            x_disp=nine_point_x(3,:);
            down2_disp_x=second_order_interpolation(x_disp,posi_x,floor_x,1,d_x,d_y,1);
            y_disp=nine_point_y(3,:);
            down2_disp_y=second_order_interpolation(y_disp,posi_x,floor_x,1,d_x,d_y,1);
            x_disp=nine_point_x(2,:);
            down_disp_x=second_order_interpolation(x_disp,posi_x,floor_x,1,d_x,d_y,1);
            y_disp=nine_point_y(2,:);
            down_disp_y=second_order_interpolation(y_disp,posi_x,floor_x,1,d_x,d_y,1);
            x_disp=nine_point_x(1,:);
            upper_disp_x=second_order_interpolation(x_disp,posi_x,floor_x,1,d_x,d_y,1);
            y_disp=nine_point_y(1,:);
            upper_disp_y=second_order_interpolation(y_disp,posi_x,floor_x,1,d_x,d_y,1);
            x_disp=[down2_disp_x;down_disp_x;upper_disp_x];
            deri_y_disp_x=second_order_interpolation(x_disp,posi_y,floor_y,0,d_x,d_x,2);
            y_disp=[down2_disp_y;down_disp_y;upper_disp_y];
            deri_y_disp_y=second_order_interpolation(y_disp,posi_y,floor_y,0,d_x,d_x,2);
            results(1)=deri_y_disp_x;
            results(2)=deri_y_disp_y;
        end
    elseif(rela_point_posi==2)
        ceil_x=center_coord(1);
        floor_y=center_coord(2);
        if(deri_direction==1)
            x_disp=nine_point_x(3:-1:1,1);
            left2_disp_x=second_order_interpolation(x_disp,posi_y,floor_y,0,d_x,d_y,1);
            y_disp=nine_point_y(3:-1:1,1);
            left2_disp_y=second_order_interpolation(y_disp,posi_y,floor_y,0,d_x,d_y,1);
            x_disp=nine_point_x(3:-1:1,2);
            left_disp_x=second_order_interpolation(x_disp,posi_y,floor_y,0,d_x,d_y,1);
            y_disp=nine_point_y(3:-1:1,2);
            left_disp_y=second_order_interpolation(y_disp,posi_y,floor_y,0,d_x,d_y,1);
            x_disp=nine_point_x(3:-1:1,3);
            right_disp_x=second_order_interpolation(x_disp,posi_y,floor_y,0,d_x,d_y,1);
            y_disp=nine_point_y(3:-1:1,3);
            right_disp_y=second_order_interpolation(y_disp,posi_y,floor_y,0,d_x,d_y,1);
            x_disp=[left2_disp_x;left_disp_x;right_disp_x];
            deri_x_disp_x=second_order_interpolation(x_disp,posi_x,ceil_x,1,d_x,d_y,2);
            y_disp=[left2_disp_y;left_disp_y;right_disp_y];
            deri_x_disp_y=second_order_interpolation(y_disp,posi_x,ceil_x,1,d_x,d_y,2);
            results(1)=deri_x_disp_x;
            results(2)=deri_x_disp_y;
        else
            x_disp=nine_point_x(3,:);
            down2_disp_x=second_order_interpolation(x_disp,posi_x,ceil_x,1,d_x,d_y,1);
            y_disp=nine_point_y(3,:);
            down2_disp_y=second_order_interpolation(y_disp,posi_x,ceil_x,1,d_x,d_y,1);
            x_disp=nine_point_x(2,:);
            down_disp_x=second_order_interpolation(x_disp,posi_x,ceil_x,1,d_x,d_y,1);
            y_disp=nine_point_y(2,:);
            down_disp_y=second_order_interpolation(y_disp,posi_x,ceil_x,1,d_x,d_y,1);
            x_disp=nine_point_x(1,:);
            upper_disp_x=second_order_interpolation(x_disp,posi_x,ceil_x,1,d_x,d_y,1);
            y_disp=nine_point_y(1,:);
            upper_disp_y=second_order_interpolation(y_disp,posi_x,ceil_x,1,d_x,d_y,1);
            x_disp=[down2_disp_x;down_disp_x;upper_disp_x];
            deri_y_disp_x=second_order_interpolation(x_disp,posi_y,floor_y,0,d_x,d_x,2);
            y_disp=[down2_disp_y;down_disp_y;upper_disp_y];
            deri_y_disp_y=second_order_interpolation(y_disp,posi_y,floor_y,0,d_x,d_x,2);
            results(1)=deri_y_disp_x;
            results(2)=deri_y_disp_y;
        end
    elseif(rela_point_posi==3)
        ceil_x=center_coord(1);
        ceil_y=center_coord(2);
        if(deri_direction==1)
            x_disp=nine_point_x(3:-1:1,1);
            left2_disp_x=second_order_interpolation(x_disp,posi_y,ceil_y,0,d_x,d_y,1);
            y_disp=nine_point_y(3:-1:1,1);
            left2_disp_y=second_order_interpolation(y_disp,posi_y,ceil_y,0,d_x,d_y,1);
            x_disp=nine_point_x(3:-1:1,2);
            left_disp_x=second_order_interpolation(x_disp,posi_y,ceil_y,0,d_x,d_y,1);
            y_disp=nine_point_y(3:-1:1,2);
            left_disp_y=second_order_interpolation(y_disp,posi_y,ceil_y,0,d_x,d_y,1);
            x_disp=nine_point_x(3:-1:1,3);
            right_disp_x=second_order_interpolation(x_disp,posi_y,ceil_y,0,d_x,d_y,1);
            y_disp=nine_point_y(3:-1:1,3);
            right_disp_y=second_order_interpolation(y_disp,posi_y,ceil_y,0,d_x,d_y,1);
            x_disp=[left2_disp_x;left_disp_x;right_disp_x];
            deri_x_disp_x=second_order_interpolation(x_disp,posi_x,ceil_x,1,d_x,d_y,2);
            y_disp=[left2_disp_y;left_disp_y;right_disp_y];
            deri_x_disp_y=second_order_interpolation(y_disp,posi_x,ceil_x,1,d_x,d_y,2);
            results(1)=deri_x_disp_x;
            results(2)=deri_x_disp_y;
        else
            x_disp=nine_point_x(3,:);
            down2_disp_x=second_order_interpolation(x_disp,posi_x,ceil_x,1,d_x,d_y,1);
            y_disp=nine_point_y(3,:);
            down2_disp_y=second_order_interpolation(y_disp,posi_x,ceil_x,1,d_x,d_y,1);
            x_disp=nine_point_x(2,:);
            down_disp_x=second_order_interpolation(x_disp,posi_x,ceil_x,1,d_x,d_y,1);
            y_disp=nine_point_y(2,:);
            down_disp_y=second_order_interpolation(y_disp,posi_x,ceil_x,1,d_x,d_y,1);
            x_disp=nine_point_x(1,:);
            upper_disp_x=second_order_interpolation(x_disp,posi_x,ceil_x,1,d_x,d_y,1);
            y_disp=nine_point_y(1,:);
            upper_disp_y=second_order_interpolation(y_disp,posi_x,ceil_x,1,d_x,d_y,1);
            x_disp=[down2_disp_x;down_disp_x;upper_disp_x];
            deri_y_disp_x=second_order_interpolation(x_disp,posi_y,ceil_y,0,d_x,d_x,2);
            y_disp=[down2_disp_y;down_disp_y;upper_disp_y];
            deri_y_disp_y=second_order_interpolation(y_disp,posi_y,ceil_y,0,d_x,d_x,2);
            results(1)=deri_y_disp_x;
            results(2)=deri_y_disp_y;
        end
    elseif(rela_point_posi==4)
        floor_x=center_coord(1);
        ceil_y=center_coord(2);
        if(deri_direction==1)
            x_disp=nine_point_x(3:-1:1,1);
            left2_disp_x=second_order_interpolation(x_disp,posi_y,ceil_y,0,d_x,d_y,1);
            y_disp=nine_point_y(3:-1:1,1);
            left2_disp_y=second_order_interpolation(y_disp,posi_y,ceil_y,0,d_x,d_y,1);
            x_disp=nine_point_x(3:-1:1,2);
            left_disp_x=second_order_interpolation(x_disp,posi_y,ceil_y,0,d_x,d_y,1);
            y_disp=nine_point_y(3:-1:1,2);
            left_disp_y=second_order_interpolation(y_disp,posi_y,ceil_y,0,d_x,d_y,1);
            x_disp=nine_point_x(3:-1:1,3);
            right_disp_x=second_order_interpolation(x_disp,posi_y,ceil_y,0,d_x,d_y,1);
            y_disp=nine_point_y(3:-1:1,3);
            right_disp_y=second_order_interpolation(y_disp,posi_y,ceil_y,0,d_x,d_y,1);
            x_disp=[left2_disp_x;left_disp_x;right_disp_x];
            deri_x_disp_x=second_order_interpolation(x_disp,posi_x,floor_x,1,d_x,d_y,2);
            y_disp=[left2_disp_y;left_disp_y;right_disp_y];
            deri_x_disp_y=second_order_interpolation(y_disp,posi_x,floor_x,1,d_x,d_y,2);
            results(1)=deri_x_disp_x;
            results(2)=deri_x_disp_y;
        else
            x_disp=nine_point_x(3,:);
            down2_disp_x=second_order_interpolation(x_disp,posi_x,floor_x,1,d_x,d_y,1);
            y_disp=nine_point_y(3,:);
            down2_disp_y=second_order_interpolation(y_disp,posi_x,floor_x,1,d_x,d_y,1);
            x_disp=nine_point_x(2,:);
            down_disp_x=second_order_interpolation(x_disp,posi_x,floor_x,1,d_x,d_y,1);
            y_disp=nine_point_y(2,:);
            down_disp_y=second_order_interpolation(y_disp,posi_x,floor_x,1,d_x,d_y,1);
            x_disp=nine_point_x(1,:);
            upper_disp_x=second_order_interpolation(x_disp,posi_x,floor_x,1,d_x,d_y,1);
            y_disp=nine_point_y(1,:);
            upper_disp_y=second_order_interpolation(y_disp,posi_x,floor_x,1,d_x,d_y,1);
            x_disp=[down2_disp_x;down_disp_x;upper_disp_x];
            deri_y_disp_x=second_order_interpolation(x_disp,posi_y,ceil_y,0,d_x,d_x,2);
            y_disp=[down2_disp_y;down_disp_y;upper_disp_y];
            deri_y_disp_y=second_order_interpolation(y_disp,posi_y,ceil_y,0,d_x,d_x,2);
            results(1)=deri_y_disp_x;
            results(2)=deri_y_disp_y;
        end
    end
end